insert into app.products (id, name, description, price) values (1, 'Caresa', 'Remirez', 50.06);
insert into app.products (id, name, description, price) values (2, 'Harvey', 'Trayte', 2.93);
insert into app.products (id, name, description, price) values (3, 'Dewie', 'Gavahan', 82.09);
insert into app.products (id, name, description, price) values (4, 'Garold', 'Shoppee', 21.13);
insert into app.products (id, name, description, price) values (5, 'Shurlock', 'Candelin', 5.48);
insert into app.products (id, name, description, price) values (6, 'Thacher', 'Waddell', 54.4);
insert into app.products (id, name, description, price) values (7, 'Reggie', 'Mattecot', 85.68);
insert into app.products (id, name, description, price) values (8, 'Kacey', 'Reye', 69.97);
insert into app.products (id, name, description, price) values (9, 'Tymon', 'Harriskine', 80.27);
insert into app.products (id, name, description, price) values (10, 'Janenna', 'Kroch', 4.99);
insert into app.products (id, name, description, price) values (11, 'Lyssa', 'Edison', 30.28);
insert into app.products (id, name, description, price) values (12, 'Marin', 'Vickers', 12.05);
insert into app.products (id, name, description, price) values (13, 'Lezlie', 'Kusick', 88.65);
insert into app.products (id, name, description, price) values (14, 'Elspeth', 'Laurand', 78.9);
insert into app.products (id, name, description, price) values (15, 'Aldric', 'Neilan', 66.23);
insert into app.products (id, name, description, price) values (16, 'Devin', 'Cadell', 17.43);
insert into app.products (id, name, description, price) values (17, 'Woodrow', 'Abramsky', 85.8);
insert into app.products (id, name, description, price) values (18, 'Chick', 'Yeiles', 61.38);
insert into app.products (id, name, description, price) values (19, 'Georas', 'Hutchinson', 2.81);
insert into app.products (id, name, description, price) values (20, 'Eleonora', 'Linskill', 44.82);
insert into app.products (id, name, description, price) values (21, 'Jodie', 'Anthonsen', 6.89);
insert into app.products (id, name, description, price) values (22, 'Harriett', 'Lockhead', 35.22);
insert into app.products (id, name, description, price) values (23, 'Welch', 'Gawthrope', 71.97);
insert into app.products (id, name, description, price) values (24, 'Letisha', 'Phalip', 80.73);
insert into app.products (id, name, description, price) values (25, 'Guenna', 'Reicharz', 30.7);
insert into app.products (id, name, description, price) values (26, 'Arnuad', 'Ollivierre', 92.58);
insert into app.products (id, name, description, price) values (27, 'Zarla', 'MacGinley', 82.3);
insert into app.products (id, name, description, price) values (28, 'Gerianne', 'Scrooby', 57.38);
insert into app.products (id, name, description, price) values (29, 'Filide', 'Spada', 94.07);
insert into app.products (id, name, description, price) values (30, 'Lowell', 'Albasini', 14.77);
insert into app.products (id, name, description, price) values (31, 'Jermaine', 'O''Kynsillaghe', 55.98);
insert into app.products (id, name, description, price) values (32, 'Annemarie', 'Wardroper', 75.07);
insert into app.products (id, name, description, price) values (33, 'Jaquith', 'McSkeagan', 33.38);
insert into app.products (id, name, description, price) values (34, 'Roseanna', 'Leward', 31.55);
insert into app.products (id, name, description, price) values (35, 'Torre', 'Luckin', 42.5);
insert into app.products (id, name, description, price) values (36, 'Odille', 'Pratten', 90.16);
insert into app.products (id, name, description, price) values (37, 'Giraldo', 'Langmead', 6.85);
insert into app.products (id, name, description, price) values (38, 'Brantley', 'Union', 99.69);
insert into app.products (id, name, description, price) values (39, 'Emlyn', 'Pettyfar', 63.5);
insert into app.products (id, name, description, price) values (40, 'Arel', 'Hrynczyk', 10.51);
insert into app.products (id, name, description, price) values (41, 'Emiline', 'Gepp', 13.22);
insert into app.products (id, name, description, price) values (42, 'Natty', 'Bewshire', 61.89);
insert into app.products (id, name, description, price) values (43, 'Stephani', 'Jaqueminet', 29.66);
insert into app.products (id, name, description, price) values (44, 'Carr', 'Towey', 46.73);
insert into app.products (id, name, description, price) values (45, 'Floria', 'Runciman', 37.07);
insert into app.products (id, name, description, price) values (46, 'Emilia', 'Sonschein', 93.57);
insert into app.products (id, name, description, price) values (47, 'Geoffrey', 'Senyard', 20.4);
insert into app.products (id, name, description, price) values (48, 'Brew', 'Gager', 40.97);
insert into app.products (id, name, description, price) values (49, 'Ulises', 'Westnage', 18.59);
insert into app.products (id, name, description, price) values (50, 'Grant', 'Favelle', 27.99);
insert into app.products (id, name, description, price) values (51, 'Laraine', 'Hickin', 54.71);
insert into app.products (id, name, description, price) values (52, 'Antonietta', 'Stigell', 76.55);
insert into app.products (id, name, description, price) values (53, 'Belicia', 'Kidstone', 92.28);
insert into app.products (id, name, description, price) values (54, 'Marti', 'Litherland', 52.44);
insert into app.products (id, name, description, price) values (55, 'Elwin', 'Wenderott', 15.52);
insert into app.products (id, name, description, price) values (56, 'Carling', 'Zapatero', 74.92);
insert into app.products (id, name, description, price) values (57, 'Felisha', 'Kilshaw', 10.02);
insert into app.products (id, name, description, price) values (58, 'Hewe', 'Melton', 95.98);
insert into app.products (id, name, description, price) values (59, 'Sander', 'Creenan', 96.41);
insert into app.products (id, name, description, price) values (60, 'Dulci', 'Ingerfield', 65.15);
insert into app.products (id, name, description, price) values (61, 'Frayda', 'Ogers', 46.74);
insert into app.products (id, name, description, price) values (62, 'Jerry', 'Thornthwaite', 69.42);
insert into app.products (id, name, description, price) values (63, 'Ninon', 'Hought', 20.86);
insert into app.products (id, name, description, price) values (64, 'Gloriana', 'Cownden', 19.49);
insert into app.products (id, name, description, price) values (65, 'Matilda', 'Tweedie', 93.99);
insert into app.products (id, name, description, price) values (66, 'Monah', 'Leeburn', 64.58);
insert into app.products (id, name, description, price) values (67, 'Neale', 'Luckham', 83.74);
insert into app.products (id, name, description, price) values (68, 'Ky', 'Ebbrell', 51.15);
insert into app.products (id, name, description, price) values (69, 'Ibrahim', 'Guppie', 13.18);
insert into app.products (id, name, description, price) values (70, 'Delly', 'Braisby', 38.18);
insert into app.products (id, name, description, price) values (71, 'Ardeen', 'Lightowlers', 6.32);
insert into app.products (id, name, description, price) values (72, 'Christi', 'Eyers', 67.6);
insert into app.products (id, name, description, price) values (73, 'Hamnet', 'Stanbro', 72.66);
insert into app.products (id, name, description, price) values (74, 'Aron', 'Malkie', 43.61);
insert into app.products (id, name, description, price) values (75, 'Raffaello', 'Vigne', 2.64);
insert into app.products (id, name, description, price) values (76, 'Herrick', 'Mitchelson', 46.64);
insert into app.products (id, name, description, price) values (77, 'Hayward', 'Binch', 2.16);
insert into app.products (id, name, description, price) values (78, 'Boigie', 'Strugnell', 41.11);
insert into app.products (id, name, description, price) values (79, 'Bart', 'Livzey', 95.56);
insert into app.products (id, name, description, price) values (80, 'Gunter', 'Cockle', 58.31);
insert into app.products (id, name, description, price) values (81, 'Deane', 'Markie', 52.62);
insert into app.products (id, name, description, price) values (82, 'Sasha', 'Parram', 4.02);
insert into app.products (id, name, description, price) values (83, 'Menard', 'Wretham', 85.03);
insert into app.products (id, name, description, price) values (84, 'Jeri', 'La Batie', 32.72);
insert into app.products (id, name, description, price) values (85, 'Riane', 'Indruch', 43.14);
insert into app.products (id, name, description, price) values (86, 'Vania', 'Evesque', 84.57);
insert into app.products (id, name, description, price) values (87, 'Alyse', 'Ibbitt', 92.98);
insert into app.products (id, name, description, price) values (88, 'Kris', 'O''Mullally', 64.65);
insert into app.products (id, name, description, price) values (89, 'Augustina', 'Popping', 18.94);
insert into app.products (id, name, description, price) values (90, 'Meriel', 'Leonarde', 60.16);
insert into app.products (id, name, description, price) values (91, 'Valentia', 'Pengelly', 54.68);
insert into app.products (id, name, description, price) values (92, 'Vanya', 'Ruller', 88.15);
insert into app.products (id, name, description, price) values (93, 'Benn', 'Brownlee', 48.43);
insert into app.products (id, name, description, price) values (94, 'Donny', 'Goady', 79.57);
insert into app.products (id, name, description, price) values (95, 'Averil', 'Akid', 46.69);
insert into app.products (id, name, description, price) values (96, 'Joya', 'Hooks', 37.36);
insert into app.products (id, name, description, price) values (97, 'Grayce', 'Imrie', 5.3);
insert into app.products (id, name, description, price) values (98, 'Pepe', 'Duffan', 56.59);
insert into app.products (id, name, description, price) values (99, 'Ardyth', 'Grundwater', 12.96);
insert into app.products (id, name, description, price) values (100, 'Arv', 'Cuss', 36.39);

INSERT INTO app.customer_address (street, city, zip_code, country, id) VALUES
    ('123 Main St', 'City1', '12345', 'Country1', 1),
    ('456 Elm St', 'City2', '67890', 'Country2', 2),
    ('789 Oak St', 'City3', '54321', 'Country3', 3);

INSERT INTO app.customer (id,first_name, last_name, email,phone,address_id) VALUES
    (1,'John', 'Doe', 'john@example.com',45657676768,1),
    (2,'Jane', 'Smith', 'jane@example.com',87806465343,2),
    (3,'Bob', 'Johnson', 'bob@example.com',4346468622,3);

